
'''
-- 코드를 입력하세요
SELECT
P.CART_ID,
IF(SUM(P.PRICE) < C.MINIMUM_REQUIREMENT, 1, 0) AS ABUSED
FROM CART_PRODUCTS P
LEFT JOIN COUPONS C ON C.CART_ID = P.CART_ID
WHERE
C.MINIMUM_REQUIREMENT IS NOT NULL
GROUP BY P.CART_ID
'''